# Generated by Django 5.0.2 on 2024-03-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='images/')),
                ('converted_image', models.FileField(blank=True, max_length=500, null=True, upload_to='converted_images/')),
            ],
        ),
    ]
